### ISSUE TITLE
It strips out or randomly "sanitises" parts of the code I put in?

### ISSUE THREAD

**Issue by josephrocca** [WebberZone/add-to-all#6]
When I try to add this in the `HTML to add after the content` box:
```html
<script>
// ...
var adBlockCode = "<div style='width:100%; height:auto;'> "
+ "<p style='margin-bottom: 0; text-align: center; font-size: 80%;'>blahblah</p> "
+ "<script async src='//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js'></scr"+"ipt> "
+ "<!-- blah blah --> "
+ "<ins class='adsbygoogle' style='display:block'  data-ad-client='ca-pub-blahblah'  data-ad-slot='blahblah'  data-ad-format='auto'></ins>"
+ "<scr"+"ipt>(adsbygoogle = window.adsbygoogle || []).push({});</scr"+"ipt> "
+ "</div>";
// ...
</script>
```

And then click save, it results in this:
```html
<script>
// ...
var adBlockCode = "<div style='width:100%;height:auto'> "
+ "<p style='margin-bottom: 0;text-align: center;font-size: 80%'>blahblah</p> "
+ "<script async src='//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js'> "
+ "<!-- blah blah --> "
+ "<ins class='adsbygoogle'></ins>"
+ "(adsbygoogle = window.adsbygoogle || []).push({}); "
+ "</div>";
// ...
</script>
```

Notice that the `style` and `data-ad-client` and `data-ad-slot` and `data-ad-format` attributes have been stripped from the `ins` tag, and that the `"<scr"+"ipt>"` parts are missing from both sides of the `(adsbygoogle = ...` code.

I have no idea what's going on here. Are you trying to sanitise the input in some way? It also strips out backslashes which is a bit strange.

**Comment by ajaydsouza** [comment]
It's WordPress' sanitisation functions that I added which have ended up overly restricting the plugin. It's something I'm going to role back in a version coming out next.

The fastest way to disable this for now is to comment out / delete this line in the plugin.

https://github.com/ajaydsouza/add-to-all/blob/v1.2.1/includes/admin/save-settings.php#L184

`add_filter( 'ata_settings_sanitize_textarea', 'ata_sanitize_textarea_field' );`

**Comment by ajaydsouza** [comment]
Filter disabled in https://github.com/ajaydsouza/add-to-all/commit/eec408bc3e5fc3299352692ec11aad20c94e8533
